name = "Lincege"
uuid = "f7bb31c1-1dce-4f9f-a981-827e9ac9009b"
version = "1.0.0"
authors = ["Pranav Seetharaman <pranav@myrdd.info> and contributors"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NautyGraphs = "7509a0a4-015a-4167-b44b-0799a1a2605e"

[weakdeps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
LincegePlotsExt = ["Plots", "ColorSchemes"]

[compat]
ColorSchemes = "3.31.0"
JSON = "1.5.0"
LinearAlgebra = "1.11"
NautyGraphs = "0.6.3"
Plots = "1.41.6"
julia = "1.11"

[extras]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots", "ColorSchemes"]
