"""
    AbstractPhysicsSolver

Abstract base type for calculating the physical observables of a single cluster. This serves as a reference implementation of the NLCE algorithm and a test set to ensure that the clusters are generated correctly.

Subtypes must implement:
- `eigenvalues()` — eigenvalues of the cluster with respect to the model
- `eigenvectors()` — eigenvectors of the cluster with respect to the model
- `cluster_weights()` — NLCE weights of the cluster generated by LINCEGE.jl
"""
abstract type AbstractPhysicsSolver end

eigenvalues(::AbstractPhysicsSolver) = _NI("eigenvalues")
eigenvectors(::AbstractPhysicsSolver) = _NI("eigenvectors")
cluster_weights(::AbstractPhysicsSolver) = _NI("cluster_weights")

function observables(solver::AbstractPhysicsSolver, betas::Vector{Float64})
        Es = eigenvalues(solver)
        Es2 = Es .^ 2
        boltzmanns = similar(Es)
        n = length(betas)
        energy = Vector{Float64}(undef, n)
        specific_heat = Vector{Float64}(undef, n)
        entropy = Vector{Float64}(undef, n)

        for (i, beta) in enumerate(betas)
                boltzmanns .= exp.(-beta .* Es)
                Z = sum(boltzmanns)
                e = dot(Es, boltzmanns) / Z
                energy[i] = e
                specific_heat[i] = beta^2 * (dot(Es2, boltzmanns) / Z - e^2)
                entropy[i] = log(Z) + beta * e
        end

        (energy=energy, specific_heat=specific_heat, entropy=entropy)
end

include("Ising.jl")
include("NLCE.jl")
