using LinearAlgebra
using AlgebraicNumbers: AlgebraicNumber

function Base.isless(a::AlgebraicNumber, b::AlgebraicNumber)
    return ((-a.coeff[1]) < (-b.coeff[1]))
end

function Base.AbstractFloat(a::AlgebraicNumber)
    return (Float64(-a.coeff[1]))
end

"""
    find_minimum_dist(coordinates, minimums=1)

Find minimum distances in a vector of coordinates up to the number of minimums
specified. Takes in coordinates of any dimension

```julia-repl
julia> find_minimum_dist([0, 0], [[0, 0], [0, 1], [1, 0]], 2)
2-element Vector{Float64}:
 0.0
 1.0
"""
function find_minimum_dist(
    center::Vector{T},
    coordinates::Vector{Vector{T}},
    minimums = 1,
) where {T<:Union{Real,Int,Float64,AlgebraicNumber}}
    relative_distances::Vector{AlgebraicNumber} =
        collect(Iterators.map(coord -> sum((coord - center) .^ 2), coordinates))
    unique!(relative_distances)
    sort!(relative_distances)
    relative_distances[1:minimums]
end

"""
    generate_coordinates(basis, bravais_lattice, max_order)

Find every coordinate generated by the bravais lattice up till maximum_order,
then repeat for every element of the basis.

```julia-repl
julia> generate_coordinates([[0, 0]], [[0, 1], [1, 0]], 3)
"""
function generate_coordinates(
    basis::Vector{Vector{T}},
    bravais_lattice::Vector{Vector{T}},
    max_order::Int64,
) where {T<:Union{Real,Int,Float64,AlgebraicNumber}}
    dimensions = size(bravais_lattice)[1]
    coordinates::Vector{Vector{T}} = []
    # Cover each basis
    for basis_elem in basis
        # Generate all integers for coordinates in that basis
        for int_coord = 0:((max_order^dimensions)-1)
            coordinate = []
            int_coord_temp = divrem(int_coord, max_order)
            # Find each coordinate 
            for dimension = 1:dimensions
                pushfirst!(coordinate, int_coord_temp[2])
                int_coord_temp = divrem(int_coord_temp[1], max_order)
            end
            # Shift according to the bravais lattice and basis
            push!(coordinates, sum(coordinate .* bravais_lattice) .+ basis_elem)
        end
    end
    coordinates
end

"""
"""
function generate_lattice(
    basis::Vector{Vector{T}},
    bravais_lattice::Vector{Vector{T}},
    neighborhood::Int,
    max_order::Int,
) where {T<:Union{Real,Int,Float64,AlgebraicNumber}}

    generated_lattice = MetaGraph(
        DiGraph();
        label_type = Int,
        vertex_data_type = Vector{T},
        edge_data_type = NTuple{2,Int},
        graph_data = "Cluster Generated by bravais lattice $bravais_lattice and basis $basis, up to maximum order $max_order, with $neighborhood nearest neighbors",
    )

    # First populate the graph with all possible vertices
    full_lattice = generate_coordinates(basis, bravais_lattice, max_order)
    for (index_coord, coord) in enumerate(full_lattice)
        generated_lattice[index_coord] = coord
    end

    # Find the center and possible distances, directions to be populated later
    center = sum(repeat([div(max_order, 2)], size(bravais_lattice)[1]) .* bravais_lattice)
    distances = find_minimum_dist(center, full_lattice, neighborhood + 1)
    directions::Vector{Vector{T}} = []

    for (index_coord, coord) in enumerate(full_lattice)
        for (index_distance, distance) in enumerate(distances[2:end])
            # This looks weird, but its because the distance array is indexed again from the 
            # second element in the enumerate function
            within_distance =
                n -> distances[index_distance] < sqrt(sum((coord - n[2]) .^ 2)) <= distance
            # Find all neighbors within the current distance but after the last distance
            for (index_neighbor, neighbor) in
                filter(within_distance, collect(enumerate(full_lattice)))
                direction = neighbor - coord
                # Check the direction of the bond, ie, along which axis
                if direction in directions
                    generated_lattice[index_coord, index_neighbor] =
                        (index_distance, findfirst(==(direction), directions))
                else
                    append!(directions, [direction])
                    generated_lattice[index_coord, index_neighbor] =
                        (index_distance, findfirst(==(direction), directions))
                end
            end
        end
    end


    (generated_lattice, findfirst(==(center), full_lattice))

end
