"""
Generation functions to create NLCE Lattices
"""

"""
    generate_coordinates(basis, bravais_lattice, max_order)

Find every coordinate generated by the bravais lattice up till maximum_order,
then repeat for every element of the basis.

```julia-repl
julia> generate_coordinates([[0, 0]], [[0, 1], [1, 0]], 3)
"""
function generate_coordinates(
    basis::Vector{Vector{T}},
    bravais_lattice::Vector{Vector{T}},
    max_order::Int64,
) where {T<:Real}
    dimensions = size(bravais_lattice)[1]
    coordinates::Vector{Vector{T}} = []
    # Cover each basis
    for basis_elem in basis
        # Generate all integers for coordinates in that basis
        for int_coord = 0:((max_order^dimensions)-1)
            coordinate = []
            int_coord_temp = divrem(int_coord, max_order)
            # Find each coordinate 
            for dimension = 1:dimensions
                pushfirst!(coordinate, int_coord_temp[2])
                int_coord_temp = divrem(int_coord_temp[1], max_order)
            end
            # Shift according to the bravais lattice and basis
            push!(coordinates, sum(coordinate .* bravais_lattice) .+ basis_elem)
        end
    end
    coordinates
end

"""
"""
function generate_lattice(
    basis::Vector{Vector{T}},
    primitive_vectors::Vector{Vector{T}},
    neighborhood::Vector{T},
    max_order::Int,
) where {T<:Real}

    coordinates = generate_coordinates(basis, primitive_vectors, max_order)

    adj_list::Vector{Vector{Int64}} = [] 
    adj_list_iso::Vector{Vector{Int64}} = [] 
    adj_list_trans::Vector{Vector{Int64}} = [] 

    directions::Vector{Vector{T}} = []

    for (index_coord, coord) in enumerate(coordinates)
        push!(adj_list, [])
        push!(adj_list_iso, [])
        push!(adj_list_trans, [])
        for (index_distance, distance) in enumerate(neighborhood)
            within_distance =
                n -> sqrt(sum((coord - n[2]) .^ 2)) ≈ distance
            # Find all neighbors within the current distance but after the last distance
            for (index_neighbor, neighbor) in
                filter(within_distance, collect(enumerate(coordinates)))
                direction = neighbor - coord
                # Check the direction of the bond, ie, along which axis
                if direction in directions
                    append!(adj_list[index_coord], index_neighbor)
                    append!(adj_list_trans[index_coord], findfirst(==(direction), directions))
                    append!(adj_list_iso[index_coord], index_distance)
                else
                    append!(directions, [direction])
                    append!(adj_list[index_coord], index_neighbor)
                    append!(adj_list_trans[index_coord], findfirst(==(direction), directions))
                    append!(adj_list_iso[index_coord], index_distance)
                end
            end
        end
    end

    NLCELattice(ones(Int64, length(adj_list)), adj_list, [adj_list_iso, adj_list_trans], false, false, false)
    
end
