"""
General utility functions for a variety of parts of the NLCE process, these
will generally be math heavy functions that are used often
"""

"""
Find every coordinate generated by the primitive_vectors up till maximum_order, then repeat for every element of the basis.
"""
function generate_coordinates(
    basis::AbstractVector{<:AbstractVector{<:Real}},
    primitive_vectors::AbstractVector{<:AbstractVector{<:Real}},
    max_order::Integer,
    basis_colors::AbstractVector{<:Integer},
)
    dimensions = length(primitive_vectors)
    coordinates::Vector{Vector{Real}} = []
    colors::Vector{Int} = []
    centers::Vector{Int} = []
    total_per_basis = max_order^dimensions
    # Cover each basis
    for (basis_ind, basis_elem) in enumerate(basis)
        # Generate all integers for coordinates in that basis
        for int_coord = 0:((total_per_basis)-1)
            coordinate = []
            int_coord_temp = divrem(int_coord, max_order)
            # Find each coordinate 
            for dimension = 1:dimensions
                pushfirst!(coordinate, int_coord_temp[2])
                int_coord_temp = divrem(int_coord_temp[1], max_order)
            end
            # Shift according to the primitive vectors and basis
            push!(coordinates, sum(coordinate .* primitive_vectors) .+ basis_elem)
            append!(colors, basis_colors[basis_ind])
        end
        append!(centers, (div(total_per_basis, 2) + ((basis_ind - 1) * total_per_basis)))
    end
    (coordinates, colors, centers)
end

"""
Converts adjacency list for a graph to an adjacency matrix
"""
function adj_list_to_adj_matrix(
    adj_list::AbstractVector{<:AbstractVector{<:Integer}},
    values::AbstractVector{<:AbstractVector{<:Integer}},
)

    # Find the number of vertices in the graph
    number_vertices = length(adj_list)
    # Initialize the empty adjacency matrix
    adj_matrix::Matrix{Int64} = zeros(number_vertices, number_vertices)

    # Loop over all the vertices in the adjacency list
    for (vertex, neighbors) in enumerate(adj_list)
        # Loop over all their neighbors
        for (neighbor_index, neighbor) in enumerate(neighbors)
            # Add the corresponding value to the adjacency matrix
            adj_matrix[vertex, neighbor] = values[vertex][neighbor_index]
        end
    end

    adj_matrix
end

function adj_list_to_adj_matrix(adj_list::AbstractVector{<:AbstractVector{<:Integer}})

    # Wrapper function for an adjacency list without weights. This function
    # will instead add a weight of 1 for every edge
    values = deepcopy(adj_list)
    for i = 1:length(values)
        values[i] .= 1
    end

    adj_list_to_adj_matrix(adj_list, values)
end

"""
Converts adjacency matrix for a graph to an adjacency list
"""
function adj_matrix_to_adj_list(adj_matrix::AbstractMatrix{<:Integer})

    # Find the number of vertices in the graph
    number_vertices = size(adj_matrix)[1]

    adj_list::Vector{Vector{Int64}} = []


    for i = 1:number_vertices
        neighbors = []
        for j = 1:number_vertices
            if adj_matrix[i, j] == 1
                append!(neighbors, j)
            end
        end
        push!(adj_list, neighbors)
    end

    adj_list

end

"""
Converts adjacency matrix for a graph to an edge list"""
function adj_matrix_to_edge_list(adj_matrix::AbstractMatrix{<:Integer})

    # Find the number of vertices in the graph
    number_vertices = size(adj_matrix)[1]

    edge_list::Vector{Vector{Int64}} = []

    for i = 1:number_vertices
        for j = i:number_vertices
            if adj_matrix[i, j] != 0
                push!(edge_list, [i, j, adj_matrix[i, j]])
            end
        end
    end

    edge_list

end

"""
Find the permutation group representation of a given group of transformations
on the given coordinates. 
    
"""
function find_permutations(coordinates::Vector{Vector{Real}}, centers, group)
    # Shift coordinates to the center
    permutations::Vector{Vector{Int}} = []
    center = sum(coordinates[centers]) / length(centers)
    center = coordinates[centers][2]

#    number_per_basis = div(length(coordinates), length(basis))
    for elem in group
        partial_coords = [coord - center for coord in coordinates]
        push!(permutations, replace(findfirst.(isapprox.([elem * coord for coord in partial_coords], atol=1e-5), (partial_coords,)), nothing => 1e10))
    end            
    
    println(length.(unique.(permutations)))
    permutations
end
    

  #  for center in centers
  #  new_coordinates = []

  #  println(new_coordinates)
  #  println(group[2])
  #  println([group[2] * coord for coord in new_coordinates])

  #  permutations = [] 
  #  for group_elem in group
  #      this_perm = []
  #      for coord_ch in new_coordinates
  #          temp_coord = group_elem * coord_ch
  #          for (ind, coord) in enumerate(new_coordinates)
  #              if isapprox(temp_coord, coord, atol=1e-3)
  #                  push!(this_perm, ind)
  #             # elseif isapprox(sum(temp_coord.^2), sum(coord.^2), atol=1e-4)
  #             #     if (isapprox(temp_coord[1], coord[1]) && isapprox(temp_coord[2], coord[2]))
  #             #          println("--------------")
  #             #          println(group_elem * coord_ch)
  #             #          println(coord)
  #             #      end
  #              end
  #          end
  #      end
  #      push!(permutations, this_perm)

  #     # push!(permutations, findfirst.(isapprox.([group_elem * coord for coord in new_coordinates], atol=1e-5), (new_coordinates,)))   
   # end

    #println(length(coordinates))
    #println(permutations)
#    println(length.(unique.(permutations)))
#    permutations
##end
