"""
General utility functions for a variety of parts of the NLCE process, these
will generally be math heavy functions that are used often
"""

using LinearAlgebra

#"""
#Find every coordinate generated by the primitive_vectors up till maximum_order, then repeat for every element of the basis.
#"""
#function generate_coordinates(
#    basis::AbstractVector{<:AbstractVector{<:Real}},
#    primitive_vectors::AbstractVector{<:AbstractVector{<:Real}},
#    max_order::Integer,
#    basis_colors::AbstractVector{<:Integer},
#)
#    dimensions = length(primitive_vectors)
#    coordinates::Vector{Vector{Real}} = []
#    colors::Vector{Int} = []
#    centers::Vector{Int} = []
#    total_per_basis = max_order^dimensions
#    # Cover each basis
#    for (basis_ind, basis_elem) in enumerate(basis)
#        # Generate all integers for coordinates in that basis
#        for int_coord = 0:((total_per_basis)-1)
#            coordinate = []
#            int_coord_temp = divrem(int_coord, max_order)
#            # Find each coordinate 
#            for dimension = 1:dimensions
#                pushfirst!(coordinate, int_coord_temp[2])
#                int_coord_temp = divrem(int_coord_temp[1], max_order)
#            end
#            # Shift according to the primitive vectors and basis
#            push!(coordinates, sum(coordinate .* primitive_vectors) .+ basis_elem)
#            append!(colors, basis_colors[basis_ind])
#        end
#        append!(centers, (div(total_per_basis, 2) + ((basis_ind - 1) * total_per_basis)))
#    end
#    (coordinates, colors, centers)
#end

"""
Generates a lattice from the given basis and primitive lattice vectors, colors according to
the appropriate coloring
"""
function generate_coordinates(
    basis::AbstractVector{<:AbstractVector{<:Real}},
    primitive_vectors::AbstractVector{<:AbstractVector{<:Real}},
    max_order::Integer,
    basis_colors::AbstractVector{<:Integer},
)
    primitive_lattice = generate_primitive_lattice(primitive_vectors, max_order)
    coordinates, centers = add_basis(basis, primitive_lattice)
    colors = repeat(basis_colors, size(primitive_lattice)[2])
    
    sorted_coord_perm = sortperm(coordinates)
    
    (coordinates[sorted_coord_perm], colors[sorted_coord_perm], findfirst.(isapprox.(centers), (coordinates[sorted_coord_perm], )))
end

"""
Generates the lattice by populating the basis around each site in the primitive lattice
"""
function add_basis(basis, primitive_lattice)

    centered_basis = [elem - (sum(basis) / length(basis)) for elem in basis]
    
    (collect(Iterators.flatten([[elem + site for elem in centered_basis] for site in eachcol(primitive_lattice)])), centered_basis)

end

"""
Generates every point from the primitive lattice vectors, in a cube of 
side length = 2 * maximum_order + 1 centered at the origin
"""
function generate_primitive_lattice(primitive_vectors, max_order)
   
    # rotate and stretch standard cartesian cube coordinates into primitive lattice
    stack(primitive_vectors) * generate_cartesian_coordinates(length(primitive_vectors), max_order)

end

"""
Generate every integer point in a cube of TWICE the given side length, centered around 
the origin twice the side length is necessary to make sure a point exists at the origin
"""
function generate_cartesian_coordinates(dimension, half_side_length)
    # Forces the 
    diameter = 2 * half_side_length + 1
    # Total number of coordinates for the entire lattice
    max_coords = diameter ^ dimension
    coords = repeat(transpose(0:max_coords - 1), dimension)
    
    for dim = 0:(dimension - 1)
        coords[dim + 1, :] = div.(coords[dim + 1, :], diameter ^ dim) .% diameter .- half_side_length
    end

    coords
end

"""
Converts adjacency list for a graph to an adjacency matrix
"""
function adj_list_to_adj_matrix(
    adj_list::AbstractVector{<:AbstractVector{<:Integer}},
    values::AbstractVector{<:AbstractVector{<:Integer}},
)

    # Find the number of vertices in the graph
    number_vertices = length(adj_list)
    # Initialize the empty adjacency matrix
    adj_matrix::Matrix{Int64} = zeros(number_vertices, number_vertices)

    # Loop over all the vertices in the adjacency list
    for (vertex, neighbors) in enumerate(adj_list)
        # Loop over all their neighbors
        for (neighbor_index, neighbor) in enumerate(neighbors)
            # Add the corresponding value to the adjacency matrix
            adj_matrix[vertex, neighbor] = values[vertex][neighbor_index]
        end
    end

    adj_matrix
end

function adj_list_to_adj_matrix(adj_list::AbstractVector{<:AbstractVector{<:Integer}})

    # Wrapper function for an adjacency list without weights. This function
    # will instead add a weight of 1 for every edge
    values = deepcopy(adj_list)
    for i = 1:length(values)
        values[i] .= 1
    end

    adj_list_to_adj_matrix(adj_list, values)
end

"""
Converts adjacency matrix for a graph to an adjacency list
"""
function adj_matrix_to_adj_list(adj_matrix::AbstractMatrix{<:Integer})

    # Find the number of vertices in the graph
    number_vertices = size(adj_matrix)[1]

    adj_list::Vector{Vector{Int64}} = []


    for i = 1:number_vertices
        neighbors = []
        for j = 1:number_vertices
            if adj_matrix[i, j] == 1
                append!(neighbors, j)
            end
        end
        push!(adj_list, neighbors)
    end

    adj_list

end

"""
Converts adjacency matrix for a graph to an edge list"""
function adj_matrix_to_edge_list(adj_matrix::AbstractMatrix{<:Integer})

    # Find the number of vertices in the graph
    number_vertices = size(adj_matrix)[1]

    edge_list::Vector{Vector{Int64}} = []

    for i = 1:number_vertices
        for j = i:number_vertices
            if adj_matrix[i, j] != 0
                push!(edge_list, [i, j, adj_matrix[i, j]])
            end
        end
    end

    edge_list

end

"""
Find the permutation group representation of a given group of transformations
on the given coordinates. 
    
"""
function find_permutations(coordinates, centers, group)
    # Shift coordinates to the center
    permutations::Vector{Vector{Int}} = []

    for elem in group
        push!(
            permutations,
            replace(
                findfirst.(
                    isapprox.([elem * coord for coord in coordinates], atol = 1e-5),
                    (coordinates,),
                ),
                nothing => 1e10,
            ),
        )
    end

    println(length.(unique.(permutations)))
    permutations
end
